domain: "https://kriscooke.github.io"
baseurl: "/puzzle-gif" # the subpath of your site, e.g. /blog
include: [s]
oembed_server: "https://giphy-link-previews-rqttsvyjno.now.sh/oembed/"
google_analytics_id: "UA-83290708-1"
